### PR TITLE
Updating image

### PR DESCRIPTION
**Pull request by liorkesos**
Added a more drupal friendly image of myself ;)

### CODE REVIEW

**Comment by RoySegall** [comment]
If you can - resize the image the same as the original one. if not, i'll handle that.

**Comment by liorkesos** [comment]
Please do. Next attention slot will only be tonight
Lior

**Comment by RoySegall** [comment]
Same for me.

**Comment by RoySegall** [comment]
Not good enough. I didn't managed to make it a good picture:
drupalcamp_tlv_2016

You looked all stretched.

**Pull request merged**
